"""empty message

Revision ID: 031e283c7c48
Revises: 98a629012ae0
Create Date: 2024-10-20 19:46:52.554676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031e283c7c48'
down_revision = '98a629012ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
